# KikoriTaikai Config
# List of log block IDs to count
logs:
  - OAK_LOG
  - SPRUCE_LOG
  - BIRCH_LOG
  - JUNGLE_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - MANGROVE_LOG
  - CHERRY_LOG
  - BAMBOO_BLOCK
  - CRIMSON_STEM
  - WARPED_STEM
  - PALE_OAK_LOG